### ISSUE TITLE
global:: is not supported in parameters for Attributes

### ISSUE THREAD

**Issue by Mudhoax** [Saltarelle/SaltarelleCompiler#393]
When attempting to use the global keyword within a attribute parameter we are encountering an error.

```
[DefaultMemberReflectability(global::System.Runtime.CompilerServices.MemberReflectability.PublicAndProtected)]
public class Bar
{
}
```

This causes the following exception to be thrown on build:

```
INTERNAL ERROR: System.ArgumentNullException: Value cannot be null.
   Parameter name: value
     at System.Enum.ToObject(Type enumType, Object value)
     at Saltarelle.Compiler.AttributeStore.ChangeType(Object source, Type type)
     at Saltarelle.Compiler.AttributeStore.ReadAttribute(IAttribute attr, Type attributeType)
     at Saltarelle.Compiler.AttributeStore.ReadAttributes[T](T t, IEnumerable`1 attributes, List`1 transformers)
     at Saltarelle.Compiler.AttributeStore..ctor(ICompilation compilation, IErrorReporter errorReporter)
     at Saltarelle.Compiler.Driver.CompilerDriver.Compile(CompilerOptions options). 
     Saltarelle.Compiler.targets          32
```

**Comment by erik-kallen** [comment]
This is a bug, but I think it will need to wait for version 3 before it can be fixed (the global:: prefix is not supported by NRefactory).

**Comment by geoffreymcgill** [comment]
It appears this is an issue in Bridge as well. We are investigating, and have created the following issue to track our progress:

https://github.com/bridgedotnet/Bridge/issues/2191

Closing this issue and will now track in Bridge.
